server:
  port: 4001

spring:
  application:
    name: springbootdemo

aws:
  region: cn-north-1
  bucket:
    name: s3-cn-test
  access:
    key: 333
  secret:
    key: 333
  sts:
    role:
      arn: arn:aws-cn:iam::2222:role/s3-test-role
    # aa
    roleArn: arn:aws-cn:iam::22222:role/s3-test-role
    sessionName: s3-upload-session
  # aa
  accessKeyId: 111
  secretKey: 111
  s3:
    bucket: s3-cn-test

filestorage:
  active: local
  local:
    endpoint: /home/data/oss
    bucketName: buket-template
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: pRYo5fCm9ZyVNKLA
    secretKey: Lv5yFUrBOXrNsZJVZ93XxSVl7JiNA99J
    bucketName: buket-template
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKey: LTAIkcl2bVhsEpGf
    secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
    bucketName: buket-template
    domain: https://image.d-domain.com
  tencentcos:
    endpoint: ap-guangzhou.myqcloud.com
    accessKey: LTAIkcl2bVhsEpGf
    secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
    bucketName: buket-template
  amazons3:
    endpoint: s3.cn-north-1.amazonaws.com.cn
    accessKey: LTAIkcl2bVhsEpGf
    secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
    bucketName: buket-template
  amazons3sts:
    region: cn-north-1
    accessKey: LTAIkcl2bVhsEpGf
    secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
    roleArn: arn:aws-cn:iam::11111111:role/s3-role
    roleSessionName: role-session
    bucketName: buket-template
  baidubos:
    endpoint: xxx.baidu.com
    accessKey: LTAIkcl2bVhsEpGf
    secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
    bucketName: buket-template
  huaweiobs:
    endpoint: xxx.huawei.com
    accessKey: LTAIkcl2bVhsEpGf
    secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
    bucketName: buket-template
  wangyinos:
    endpoint: xxx.wangyi.com
    accessKey: LTAIkcl2bVhsEpGf
    secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
    bucketName: buket-template-dev
  jingdongoss:
    endpoint: xxx.jdcloud.com
    accessKey: LTAIkcl2bVhsEpGf
    secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
    bucketName: buket-template-dev
